version: '3.1'

services:
  app:
    build: .
    environment:
      NODE_ENV: production
    ports:
      - '80:5000'
    links:
      - mongo

  app-dev:
    build: .
    command: npm run dev
    environment:
      NODE_ENV: dev
    ports:
      - '5000:5000'
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    image: 'mongo:4.0'
    volumes:
      - ./data:/data/db

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo